* smokejs roadmap
** Tasks for RC1
*** DONE Create a testing template for articles
    CLOSED: [2014-02-27 Thu 10:18]
*** DONE Make a function to choose the correct template
    CLOSED: [2014-03-04 Tue 11:30]
    Given the component type (article, author, etc) and the content type
    (application/x-markdown, image/png, etc), return the appropriate template.
    
**** DONE Decide how the component/content type/template mapping will be stored
     CLOSED: [2014-03-03 Mon 16:07]
     Will this be a JSON blob served up by Mirrors? Will this be built directly
     into smoke itself? Should it be generated by the Mirrors deploy but then
     pushed to the Smoke code base or something?
     
     Decision: there will be a JSON blob

**** DONE Write tests for the template chooser
     CLOSED: [2014-03-03 Mon 16:42]

**** DONE Implement context-awareness for the templates
     CLOSED: [2014-03-04 Tue 11:29]
     Specifically we want chooseTemplate to give us a different template for an
     (e.g.) image if it's the master image for an article or if it's the master
     image for a quize.

*** TODO Make a dust filter to turn markdown into html
**** TODO Write tests for the markdown->html filter
     (if it doesn't exist already)

*** TODO Hook the markdown filter into our existing render function

(This is just a markdown of the org-mode file I'm currently using to organize
this stuff. A fancier, cleaner list will be forthcoming.)
